#-------------------------------
# General Site Settings

title: LOVE ~ DEEP
description: WEDDING // FILMS // TORONTO
email: huangnor@gmail.com

# NOTE: The Logo and Background image are defined in the all.sass document.

menu:
- {name: About Me, url: '#about-me'}
- {name: Work, url: '#work'}
- {name: Clients, url: '#clients'}
- {name: Contact, url: '#contact'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Provide a description for your website to make it visible to search engines.'
  rel-author: 'https://plus.google.com/u/0/+DevTipsForDesigners/'
  rel-publisher: 'https://plus.google.com/u/0/+DevTipsForDesigners/'

#-------------------------------
# About Section

# NOTE: The avatar is defined in the all.sass document.

blurb: >
  **Norman specializes in making things** for human people.
  Most of the things he makes are [moving-pictures](https://www.youtube.com/channel/UCDlE9seYdH4aZ20UqHBjLTw/){:target="_blank"}, 
  but he also puts effort into crafting [still-images](https://www.flickr.com/photos/150616864@N03/with/49531185322/){:target="_blank"}.


skills:
- {name: Communication, value: '7'}
- {name: Organization, value: '7'}
- {name: Learning, value: '8'}
- {name: Editing, value: '3'}
- {name: Planning, value: '6'}
- {name: Lighting, value: '2'}
- {name: Filming, value: '5'}
- {name: Sound, value: '2'}

#-------------------------------
# Work Section

projects:
- {name: Jielun & Yilin, folder: 'proj-5', file: 'work/proj-5.html'}
- {name: Ted & Jennette, folder: 'proj-1', file: 'work/proj-1.html'}
- {name: Nicole & Jeremy, folder: 'proj-2', file: 'work/proj-2.html'}
- {name: Carmen & Victor, folder: 'proj-3', file: 'work/proj-3.html'}
- {name: Chen & Huilan, folder: 'proj-4', file: 'work/proj-4.html'}
- {name: Timeline Page, folder: 'proj-6', file: 'work/proj-6.html'}
- {name: Weather Dashboard, folder: 'proj-7', file: 'work/proj-7.html'}
- {name: Stripes & Co, folder: 'proj-8', file: 'work/proj-8.html'}

#-------------------------------
# Clients Section

clients:
- {avatar: 'face-aaroni.jpg',
  name: 'Scott Summers',
  title: 'Director of Design, OnToText Ind.',
  quote: '<p><strong>While we all felt that Norman was a great</strong> asset to our team — and really worked hard to understand our products from the point of view of the customer — we also all agree he should shower more often.</p>',
  logo: 'logo1.png'}
- {avatar: 'face-atariboy.jpg',
  name: 'Hank McCoy',
  title: 'Eater of Salad, Antartica Int.',
  quote: '<p><strong>Working with Norman was the highlight of my career.</strong> Other moments of note were collecting the largest number of paperclips in the office, and winning a trophy for saying "uh huh, and then what?" 30 times in a row to my girlfriend without her noticing.</p>',
  logo: 'logo2.png'}
- {avatar: 'face-jackiesaik.jpg',
  name: 'Stacy Lang',
  title: 'Social Media Girl, Quebec Int.',
  quote: '<p><strong>Yea, I guess hes good at computers or something,</strong> but let me ask you this: If a cat always lands on its feet, and buttered bread always lands butter side down, what would happen if you tied buttered bread on top of a cat?</p>',
  logo: 'logo3.png'}
- {avatar: 'face-teleject.jpg',
  name: 'Cleatus Cassidy',
  title: 'VP of Helmut, Lorem Sorem LLC.',
  quote: '<p><strong>Back in old country</strong> only nerds who is playing on computers. Now all bros is wanting to make codes and junk. I lost foot in war. You dont see girls asking me about homework.</p>',
  logo: 'logo4.png'}
  
  
#-------------------------------
# Contact Section
  
social:
- {icon: 'instagram', link: 'https://www.instagram.com/huangnor/'}
- {icon: 'facebook', link: 'https://facebook.com/Huangnor'}
- {icon: 'youtube', link: 'https://www.youtube.com/channel/UCDlE9seYdH4aZ20UqHBjLTw?view_as=subscriber'}
  
# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'